### ISSUE TITLE
Wireframe Game Tracking Page

### ISSUE THREAD

**Issue by LandGod** [LandGod/ClueHunt-QR#29]
* Page should include the standard navbar
* Page should include a link back to the dashboard
* Page should have a title which will be filled in via a js database query to have the name of the clue hunt.
* Page should have a table with the following columns (feel free to reword): 
** Clue Number
** First Finder
** Total Times Found

Column rows will be filled in via JS.

**Comment by mandres2** [comment]
8.7.19 - In progress. Established Wireframe + html page.
